// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvPaHeW3pkZ-rBYiIawKmaSjh2WVquj8',
    appId: '1:925677334086:web:4874687bc8c8337b88e447',
    messagingSenderId: '925677334086',
    projectId: 'axsptdemo',
    authDomain: 'axsptdemo.firebaseapp.com',
    storageBucket: 'axsptdemo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCggSqL22LZ4Yk7_KgxbtCmZxfX0Kge264',
    appId: '1:925677334086:android:35a504cfbce2937b88e447',
    messagingSenderId: '925677334086',
    projectId: 'axsptdemo',
    storageBucket: 'axsptdemo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDypeNZ9Ijf17j4T-V66eCmcRdhBgtEsVc',
    appId: '1:925677334086:ios:aa53cc6bd6bf43df88e447',
    messagingSenderId: '925677334086',
    projectId: 'axsptdemo',
    storageBucket: 'axsptdemo.firebasestorage.app',
    androidClientId: '925677334086-0culqddge28j2dnhc4rpt278a594n745.apps.googleusercontent.com',
    iosClientId: '925677334086-uuc94u23hsvoa3ei57jqakuae4qd6fcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDypeNZ9Ijf17j4T-V66eCmcRdhBgtEsVc',
    appId: '1:925677334086:ios:aa53cc6bd6bf43df88e447',
    messagingSenderId: '925677334086',
    projectId: 'axsptdemo',
    storageBucket: 'axsptdemo.firebasestorage.app',
    androidClientId: '925677334086-0culqddge28j2dnhc4rpt278a594n745.apps.googleusercontent.com',
    iosClientId: '925677334086-uuc94u23hsvoa3ei57jqakuae4qd6fcc.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbvPaHeW3pkZ-rBYiIawKmaSjh2WVquj8',
    appId: '1:925677334086:web:729ffd1b60b2a2dd88e447',
    messagingSenderId: '925677334086',
    projectId: 'axsptdemo',
    authDomain: 'axsptdemo.firebaseapp.com',
    storageBucket: 'axsptdemo.firebasestorage.app',
  );
}
